# This is the AIPACK lab@ako AI Pack for Agentic Knowledge Optimization
[pack]
namespace = "lab" # aipack.ai lab namespace
name      = "ako"      # pack name (so aip install lab@ako)
version   = "0.2.0-WIP"

license  = "MIT or Apache 2"
homepage = "https://aipack.ai/"
repo     = "https://github.com/aipack-ai/aipack-lab"
author   = "Jeremy Chone"
email    = "jeremy.chone@gmail.com"



